# Generated by Django 3.0.4 on 2020-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0025_auto_20200720_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('bhavya123', 'bhavya123'), ('srinivas', 'srinivas')], max_length=100, null=True),
        ),
    ]
